# Generated by Django 5.0.4 on 2024-05-15 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_alter_product_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="slug",
            field=models.SlugField(
                blank=True, max_length=150, null=True, unique=True, verbose_name="slug"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="viewed",
            field=models.IntegerField(default=0, verbose_name="Количество просмотров"),
        ),
        migrations.AlterField(
            model_name="product",
            name="photo",
            field=models.ImageField(
                blank=True,
                help_text="Загрузите фото",
                null=True,
                upload_to="product/photo",
                verbose_name="Фото",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.FloatField(help_text="Введите описание", verbose_name="Цена"),
        ),
    ]
