# Generated by Django 4.2 on 2024-06-15 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_alter_product_created_at_alter_product_updated_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["name", "category", "created_at", "updated_at"],
                "permissions": [
                    ("can_edit_category", "Edit Category"),
                    ("can_edit_description", "Edit Description"),
                    ("can_edit_is_active", "Edit Is Active"),
                ],
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
            },
        ),
    ]
